
/*
id: 101546520
node_id: "MDEwOlJlcG9zaXRvcnkxMDE1NDY1MjA="
name: "annyang"
full_name: "ddennis/annyang"
private: false
owner: {login: "ddennis", id: 300269, node_id: "MDQ6VXNlcjMwMDI2OQ==", avatar_url: "https://avatars1.githubusercontent.com/u/300269?v=4", gravatar_id: "", …}
html_url: "https://github.com/ddennis/annyang"
description: ":speech_balloon: Speech recognition for your site"
fork: true
url: "https://api.github.com/repos/ddennis/annyang"
forks_url: "https://api.github.com/repos/ddennis/annyang/forks"
keys_url: "https://api.github.com/repos/ddennis/annyang/keys{/key_id}"
collaborators_url: "https://api.github.com/repos/ddennis/annyang/collaborators{/collaborator}"
teams_url: "https://api.github.com/repos/ddennis/annyang/teams"
hooks_url: "https://api.github.com/repos/ddennis/annyang/hooks"
issue_events_url: "https://api.github.com/repos/ddennis/annyang/issues/events{/number}"
events_url: "https://api.github.com/repos/ddennis/annyang/events"
assignees_url: "https://api.github.com/repos/ddennis/annyang/assignees{/user}"
branches_url: "https://api.github.com/repos/ddennis/annyang/branches{/branch}"
tags_url: "https://api.github.com/repos/ddennis/annyang/tags"
blobs_url: "https://api.github.com/repos/ddennis/annyang/git/blobs{/sha}"
git_tags_url: "https://api.github.com/repos/ddennis/annyang/git/tags{/sha}"
git_refs_url: "https://api.github.com/repos/ddennis/annyang/git/refs{/sha}"
trees_url: "https://api.github.com/repos/ddennis/annyang/git/trees{/sha}"
statuses_url: "https://api.github.com/repos/ddennis/annyang/statuses/{sha}"
languages_url: "https://api.github.com/repos/ddennis/annyang/languages"
stargazers_url: "https://api.github.com/repos/ddennis/annyang/stargazers"
contributors_url: "https://api.github.com/repos/ddennis/annyang/contributors"
subscribers_url: "https://api.github.com/repos/ddennis/annyang/subscribers"
subscription_url: "https://api.github.com/repos/ddennis/annyang/subscription"
commits_url: "https://api.github.com/repos/ddennis/annyang/commits{/sha}"
git_commits_url: "https://api.github.com/repos/ddennis/annyang/git/commits{/sha}"
comments_url: "https://api.github.com/repos/ddennis/annyang/comments{/number}"
issue_comment_url: "https://api.github.com/repos/ddennis/annyang/issues/comments{/number}"
contents_url: "https://api.github.com/repos/ddennis/annyang/contents/{+path}"
compare_url: "https://api.github.com/repos/ddennis/annyang/compare/{base}...{head}"
merges_url: "https://api.github.com/repos/ddennis/annyang/merges"
archive_url: "https://api.github.com/repos/ddennis/annyang/{archive_format}{/ref}"
downloads_url: "https://api.github.com/repos/ddennis/annyang/downloads"
issues_url: "https://api.github.com/repos/ddennis/annyang/issues{/number}"
pulls_url: "https://api.github.com/repos/ddennis/annyang/pulls{/number}"
milestones_url: "https://api.github.com/repos/ddennis/annyang/milestones{/number}"
notifications_url: "https://api.github.com/repos/ddennis/annyang/notifications{?since,all,participating}"
labels_url: "https://api.github.com/repos/ddennis/annyang/labels{/name}"
releases_url: "https://api.github.com/repos/ddennis/annyang/releases{/id}"
deployments_url: "https://api.github.com/repos/ddennis/annyang/deployments"
created_at: "2017-08-27T10:59:47Z"
updated_at: "2017-08-27T10:59:48Z"
pushed_at: "2016-12-31T10:46:24Z"
git_url: "git://github.com/ddennis/annyang.git"
ssh_url: "git@github.com:ddennis/annyang.git"
clone_url: "https://github.com/ddennis/annyang.git"
svn_url: "https://github.com/ddennis/annyang"
homepage: "https://www.talater.com/annyang/"
size: 947
stargazers_count: 0
watchers_count: 0
language: "JavaScript"
has_issues: false
has_projects: true
has_downloads: true
has_wiki: true
has_pages: false
forks_count: 0
mirror_url: null
archived: false
disabled: false
open_issues_count: 0
license: {key: "mit", name: "MIT License", spdx_id: "MIT", url: "https://api.github.com/licenses/mit", node_id: "MDc6TGljZW5zZTEz"}
forks: 0
open_issues: 0
watchers: 0
default_branch: "master"*/

/*
{
	login: "ddennis",
		id: 300269,
	node_id: "MDQ6VXNlcjMwMDI2OQ==",
	avatar_url: "https://avatars1.githubusercontent.com/u/300269?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/ddennis",
	html_url: "https://github.com/ddennis",
	followers_url: "https://api.github.com/users/ddennis/followers",
	following_url: "https://api.github.com/users/ddennis/following{/other_user}",
	gists_url: "https://api.github.com/users/ddennis/gists{/gist_id}",
	starred_url: "https://api.github.com/users/ddennis/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/ddennis/subscriptions",
	organizations_url: "https://api.github.com/users/ddennis/orgs",
	repos_url: "https://api.github.com/users/ddennis/repos",
	events_url: "https://api.github.com/users/ddennis/events{/privacy}",
	received_events_url: "https://api.github.com/users/ddennis/received_events",
	type: "User",
	site_admin: false,
	score: 560.8415}*/
